services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: arxiv-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build:
      context: ./backend
    container_name: arxiv-rag-backend
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    working_dir: /project
    volumes:
      - ./backend:/project/backend

volumes:
  qdrant_data:
